// Regenerates gym/tests/fixtures/protocol_golden.json: the golden fixture
// consumed by gym/tests/test_protocol_golden.py. Generated BY the TS
// encoder so Python's mirrored action-code table
// (gym/warwright_gym/actions.py) is checked against the real encoder
// output, not independently invented data (see the #63 SUB_PLAN "Protocol
// round-trip (pytest)" bullet). Run via `pnpm --filter @warwright/gym-bridge
// gen-fixture`.
//
// This script lives outside the vitest include glob's runtime concerns only
// in that it needs node:fs to write the file; all actual generation logic
// lives in protocol-fixture.ts's generateProtocolFixture(), which
// protocol-fixture.test.ts also calls directly (in memory, no filesystem)
// to assert deep-equality against the committed fixture -- mirroring how
// packages/core's gen-golden.ts pairs with golden-replay.test.ts.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateProtocolFixture } from './protocol-fixture.js';

const fixture = generateProtocolFixture();

const outPath = fileURLToPath(
  new URL('../../../../gym/tests/fixtures/protocol_golden.json', import.meta.url),
);
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, JSON.stringify(fixture, null, 2) + '\n');

console.log('Wrote', outPath);
