// Regenerates gym/tests/fixtures/protocol_golden.json: the golden fixture
// consumed by gym/tests/test_protocol_golden.py. Generated BY the TS
// encoder so Python's mirrored action-code table
// (gym/warwright_gym/actions.py) is checked against the real encoder
// output, not independently invented data (see the #63 SUB_PLAN "Protocol
// round-trip (pytest)" bullet). Run via `pnpm --filter @warwright/gym-bridge
// gen-fixture`.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Action, Replay } from '@warwright/core';
import {
  OBS_SELF_FIELD_COUNT,
  OBS_UNIT_FIELD_COUNT,
  createSteppedMatch,
  encodeAction,
  encodeObservation,
  skills,
} from '@warwright/core';

const replay: Replay = {
  version: 1,
  seed: 42,
  buildA: {
    name: 'Fixture A',
    units: [
      {
        roleId: 'vanguard',
        skillIds: ['shield-bash', 'guardian-ward'],
        behaviorId: 'protect-allies',
        position: { x: 100, y: 100 },
      },
      {
        roleId: 'reaver',
        skillIds: ['cleave'],
        behaviorId: 'aggro-lowest-hp',
        position: { x: 120, y: 100 },
      },
    ],
  },
  buildB: {
    name: 'Fixture B',
    units: [
      {
        roleId: 'mender',
        skillIds: ['mending-touch'],
        behaviorId: 'protect-allies',
        position: { x: 400, y: 100 },
      },
    ],
  },
};

// step(0) advances nothing; it just returns the post-reset WorldState
// through the public SteppedTransport surface (no internal `init` import).
const transport = createSteppedMatch(replay);
const world = transport.step(0);
const vector = encodeObservation(world, 0);

const actionCases: Array<{ kind: string; action: Action; encoded: number[] }> = [
  { kind: 'idle', action: { kind: 'idle' }, encoded: [] },
  { kind: 'move', action: { kind: 'move', to: { x: 12, y: 34 } }, encoded: [] },
  { kind: 'move-toward', action: { kind: 'move-toward', targetId: 7 }, encoded: [] },
  { kind: 'attack', action: { kind: 'attack', targetId: 3 }, encoded: [] },
  {
    kind: 'cast',
    action: { kind: 'cast', skillId: 'frost-bolt', targetId: 5 },
    encoded: [],
  },
];
for (const testCase of actionCases) {
  testCase.encoded = encodeAction(testCase.action);
}

const fixture = {
  skillCatalogLength: skills.length,
  actions: actionCases,
  observation: {
    unitId: 0,
    vector,
    length: vector.length,
  },
  selfFieldCount: OBS_SELF_FIELD_COUNT,
  unitFieldCount: OBS_UNIT_FIELD_COUNT,
  numAllies: 1,
  numEnemies: 1,
};

const outPath = fileURLToPath(
  new URL('../../../../gym/tests/fixtures/protocol_golden.json', import.meta.url),
);
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, JSON.stringify(fixture, null, 2) + '\n');

console.log('Wrote', outPath);
