"""Protocol round-trip test (#63 SUB_PLAN "Protocol round-trip (pytest)"):
loads a golden fixture GENERATED by the TS encoder
(packages/gym-bridge/src/scripts/gen-protocol-fixture.ts) and re-derives it
with the Python-mirrored codec (warwright_gym/actions.py), asserting
value-equality. This is what proves Python and TypeScript agree on the
action encoding; it never re-derives the observation MATH (only the
action-kind table is mirrored in Python), but it does assert the
JSON-transported observation values round-trip as exact integers with no
float drift, that the mirrored skill catalog matches the TS content catalog
EXACTLY (order and all, not just length), and that OBS_ENCODING_VERSION
matches the TS encoder's version -- so a skill add/reorder or an encoder
layout/version change desyncs Python and TypeScript with a RED test, not
silently.

Regenerate the fixture with `pnpm --filter @warwright/gym-bridge
gen-fixture` from the repo root whenever the encoder changes.
"""

from __future__ import annotations

import json
from pathlib import Path

from warwright_gym.actions import OBS_ENCODING_VERSION, SKILL_CATALOG, decode_action, encode_action
from warwright_gym.observation import (
    OBS_SELF_FIELD_COUNT,
    OBS_UNIT_FIELD_COUNT,
    OBS_UNIT_ID_OFFSET,
    compute_observation_length,
)

FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "protocol_golden.json"


def load_fixture():
    if not FIXTURE_PATH.exists():
        raise AssertionError(
            f"{FIXTURE_PATH} is missing. Regenerate it with "
            "`pnpm --filter @warwright/gym-bridge gen-fixture` from the repo root."
        )
    return json.loads(FIXTURE_PATH.read_text())


def test_action_codec_matches_the_ts_encoder_for_every_kind():
    fixture = load_fixture()
    assert fixture["actions"], "fixture must cover at least one action kind"
    for case in fixture["actions"]:
        assert encode_action(case["action"]) == case["encoded"], case["kind"]
        assert decode_action(case["encoded"]) == case["action"], case["kind"]


def test_skill_catalog_length_matches_the_ts_content_catalog():
    fixture = load_fixture()
    assert len(SKILL_CATALOG) == fixture["skillCatalogLength"]


def test_skill_catalog_matches_the_ts_content_catalog_exactly():
    # A skill add/reorder in packages/core/src/content/data/skills.ts must
    # be caught here, not just a length check -- see the #63 review "the
    # parity fixture is generate-only" MUST-FIX finding.
    fixture = load_fixture()
    assert SKILL_CATALOG == fixture["skillCatalog"]


def test_obs_encoding_version_matches_the_ts_encoder():
    fixture = load_fixture()
    assert OBS_ENCODING_VERSION == fixture["obsEncodingVersion"]


def test_observation_vector_is_all_integers_and_the_declared_length():
    fixture = load_fixture()
    observation = fixture["observation"]
    vector = observation["vector"]

    assert len(vector) == observation["length"]
    assert all(isinstance(value, int) for value in vector)

    expected_self_field_count = 5 + len(SKILL_CATALOG)
    assert expected_self_field_count == fixture["selfFieldCount"]

    expected_length = fixture["selfFieldCount"] + fixture["unitFieldCount"] * (
        fixture["numAllies"] + fixture["numEnemies"]
    )
    assert len(vector) == expected_length


def test_observation_layout_constants_match_the_fixture():
    fixture = load_fixture()
    assert OBS_SELF_FIELD_COUNT == fixture["selfFieldCount"]
    assert OBS_UNIT_FIELD_COUNT == fixture["unitFieldCount"]


def test_unit_id_offset_is_the_first_field_of_a_unit_block():
    assert OBS_UNIT_ID_OFFSET == 0


def test_compute_observation_length_matches_the_fixture_vector_length():
    fixture = load_fixture()
    observation = fixture["observation"]
    length = compute_observation_length(fixture["numAllies"], fixture["numEnemies"])
    assert length == observation["length"]
