"""Protocol round-trip test (#63 SUB_PLAN "Protocol round-trip (pytest)"):
loads a golden fixture GENERATED by the TS encoder
(packages/gym-bridge/src/scripts/gen-protocol-fixture.ts) and re-derives it
with the Python-mirrored codec (warwright_gym/actions.py), asserting
value-equality. This is what proves Python and TypeScript agree on the
action encoding; it never re-derives the observation MATH (only the
action-kind table is mirrored in Python), but it does assert the
JSON-transported observation values round-trip as exact integers with no
float drift, and that the mirrored skill catalog stays the same length as
the TS content catalog.

Regenerate the fixture with `pnpm --filter @warwright/gym-bridge
gen-fixture` from the repo root whenever the encoder changes.
"""

from __future__ import annotations

import json
from pathlib import Path

from warwright_gym.actions import SKILL_CATALOG, decode_action, encode_action

FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "protocol_golden.json"


def load_fixture():
    if not FIXTURE_PATH.exists():
        raise AssertionError(
            f"{FIXTURE_PATH} is missing. Regenerate it with "
            "`pnpm --filter @warwright/gym-bridge gen-fixture` from the repo root."
        )
    return json.loads(FIXTURE_PATH.read_text())


def test_action_codec_matches_the_ts_encoder_for_every_kind():
    fixture = load_fixture()
    assert fixture["actions"], "fixture must cover at least one action kind"
    for case in fixture["actions"]:
        assert encode_action(case["action"]) == case["encoded"], case["kind"]
        assert decode_action(case["encoded"]) == case["action"], case["kind"]


def test_skill_catalog_length_matches_the_ts_content_catalog():
    fixture = load_fixture()
    assert len(SKILL_CATALOG) == fixture["skillCatalogLength"]


def test_observation_vector_is_all_integers_and_the_declared_length():
    fixture = load_fixture()
    observation = fixture["observation"]
    vector = observation["vector"]

    assert len(vector) == observation["length"]
    assert all(isinstance(value, int) for value in vector)

    expected_self_field_count = 5 + len(SKILL_CATALOG)
    assert expected_self_field_count == fixture["selfFieldCount"]

    expected_length = fixture["selfFieldCount"] + fixture["unitFieldCount"] * (
        fixture["numAllies"] + fixture["numEnemies"]
    )
    assert len(vector) == expected_length
