"""Mirrors packages/core/src/sim/observation.ts's Action tag table EXACTLY.

Only this kind-code table is duplicated in Python -- never any game rule
(see the #63 SUB_PLAN: "Python mirrors ONLY this codec ... never any
rule"). If packages/core/src/sim/observation.ts's encoding ever changes,
this module (and OBS_ENCODING_VERSION on the TS side) must change together;
gym/tests/test_protocol_golden.py pins the two against each other via a
fixture generated by the TS encoder.

Every encoded action is a 4-element list: [kind_code, p1, p2, p3]. Unused
slots are 0.
    idle:         [0, 0,         0,    0]
    move:         [1, to_x,      to_y, 0]
    move-toward:  [2, target_id, 0,    0]
    attack:       [3, target_id, 0,    0]
    cast:         [4, target_id, 0,    skill_index]

skill_index is the position of the skill id in the fixed content skill
catalog (packages/core/src/content/data/skills.ts, re-exported as `skills`
from the core's public index), NOT a per-unit index.
"""

from __future__ import annotations

from typing import Any

# Mirrors packages/core/src/sim/observation.ts's OBS_ENCODING_VERSION: the
# parity ground truth for the wire protocol. gym/tests/test_protocol_golden.py
# cross-checks this against the TS-generated fixture's `obsEncodingVersion`
# so a version bump on either side without the other is caught mechanically.
OBS_ENCODING_VERSION = 1

ACTION_KIND_IDLE = 0
ACTION_KIND_MOVE = 1
ACTION_KIND_MOVE_TOWARD = 2
ACTION_KIND_ATTACK = 3
ACTION_KIND_CAST = 4

# Fixed catalog order -- keep in sync with packages/core/src/content/data/skills.ts.
# gym/tests/test_protocol_golden.py cross-checks this list EXACTLY (order and
# all, not just length) against the TS-generated fixture so a skill add or
# reorder here is caught mechanically.
SKILL_CATALOG = [
    "shield-bash",
    "guardian-ward",
    "cleave",
    "frost-bolt",
    "venom-shot",
    "mending-touch",
]


def encode_action(action: dict[str, Any]) -> list[int]:
    kind = action["kind"]
    if kind == "idle":
        return [ACTION_KIND_IDLE, 0, 0, 0]
    if kind == "move":
        to = action["to"]
        return [ACTION_KIND_MOVE, to["x"], to["y"], 0]
    if kind == "move-toward":
        return [ACTION_KIND_MOVE_TOWARD, action["targetId"], 0, 0]
    if kind == "attack":
        return [ACTION_KIND_ATTACK, action["targetId"], 0, 0]
    if kind == "cast":
        skill_id = action["skillId"]
        if skill_id not in SKILL_CATALOG:
            raise ValueError(f"encode_action: unknown skillId {skill_id!r}")
        return [ACTION_KIND_CAST, action["targetId"], 0, SKILL_CATALOG.index(skill_id)]
    raise ValueError(f"encode_action: unknown action kind {kind!r}")


def _assert_unused_slots_are_zero(encoded: list[int], used_indices: tuple[int, ...]) -> None:
    # Mirrors packages/core/src/sim/observation.ts's decodeAction: a slot the
    # kind does not use MUST be 0 on the wire. encode_action never emits
    # anything but 0 there, so a non-zero unused slot means the wire
    # producer disagrees with this codec about the layout -- fail loud
    # rather than decode leniently.
    for index in range(1, len(encoded)):
        if index in used_indices:
            continue
        if encoded[index] != 0:
            raise ValueError(
                f"decode_action: unused slot {index} must be 0, got {encoded[index]} "
                f"(encoded: {encoded!r})"
            )


def decode_action(encoded: list[int]) -> dict[str, Any]:
    if len(encoded) != 4:
        raise ValueError(f"decode_action: expected a 4-element tuple, got length {len(encoded)}")
    kind_code, p1, p2, p3 = encoded

    if kind_code == ACTION_KIND_IDLE:
        _assert_unused_slots_are_zero(encoded, ())
        return {"kind": "idle"}
    if kind_code == ACTION_KIND_MOVE:
        _assert_unused_slots_are_zero(encoded, (1, 2))
        return {"kind": "move", "to": {"x": p1, "y": p2}}
    if kind_code == ACTION_KIND_MOVE_TOWARD:
        _assert_unused_slots_are_zero(encoded, (1,))
        return {"kind": "move-toward", "targetId": p1}
    if kind_code == ACTION_KIND_ATTACK:
        _assert_unused_slots_are_zero(encoded, (1,))
        return {"kind": "attack", "targetId": p1}
    if kind_code == ACTION_KIND_CAST:
        _assert_unused_slots_are_zero(encoded, (1, 3))
        if p3 < 0 or p3 >= len(SKILL_CATALOG):
            raise ValueError(f"decode_action: unknown skill index {p3}")
        return {"kind": "cast", "skillId": SKILL_CATALOG[p3], "targetId": p1}
    raise ValueError(f"decode_action: unknown action kind code {kind_code}")
